apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: monitor
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      memory_limiter:
        limit_mib: 512
      resource:
        attributes:
          - key: service.namespace
            value: "globeco"
            action: upsert
          - key: deployment.environment
            value: "production"
            action: upsert

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        # Remove namespace to avoid otel_ prefix
        const_labels:
          service_namespace: "globeco"
        # Add metric relabeling to ensure proper export
        metric_relabeling:
          - source_labels: [__name__]
            regex: '(.+)'
            target_label: __name__
            replacement: '${1}'
      debug:
        verbosity: detailed

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, resource, batch]
          exporters: [prometheus, debug]
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
