apiVersion: apps/v1
kind: Deployment
metadata:
  name: globeco-portfolio-service
  namespace: globeco
  labels:
    app: globeco-portfolio-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globeco-portfolio-service
  template:
    metadata:
      labels:
        app: globeco-portfolio-service
    spec:
      containers:
        - name: globeco-portfolio-service
          image: kasbench/globeco-portfolio-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URI
              value: "mongodb://globeco-portfolio-service-mongodb:27017"
            - name: OTEL_METRICS_LOGGING_ENABLED
              value: "true"
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "100m"
              memory: "200Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 240
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /
              port: 8000
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: globeco-portfolio-service
  namespace: globeco
spec:
  selector:
    app: globeco-portfolio-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP 