apiVersion: v1
kind: PersistentVolume
metadata:
  name: portfolio-service-mongodb-pv
  labels:
    app: portfolio-service-mongodb
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disk1/portfolio-service-mongodb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-0