apiVersion: apps/v1
kind: Deployment
metadata:
  name: globeco-portfolio-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: globeco-portfolio-service
          env:
            # Development Environment Configuration
            - name: ENVIRONMENT
              value: "development"
            - name: LOG_LEVEL
              value: "DEBUG"
            
            # Full Observability for Development
            - name: ENABLE_METRICS
              value: "true"
            - name: ENABLE_TRACING
              value: "true"
            - name: ENABLE_DATABASE_TRACING
              value: "true"
            - name: ENABLE_THREAD_METRICS
              value: "true"
            - name: ENABLE_REQUEST_LOGGING
              value: "true"
            - name: ENABLE_METRICS_MIDDLEWARE
              value: "true"
            - name: ENABLE_PERFORMANCE_PROFILING
              value: "true"
            
            # Development Sampling (100%)
            - name: TRACE_SAMPLE_RATE
              value: "1.0"
            - name: METRICS_DEBUG_LOGGING
              value: "true"
            - name: THREAD_METRICS_DEBUG_LOGGING
              value: "true"
            - name: THREAD_METRICS_UPDATE_INTERVAL
              value: "1.0"
            
            # Faster export intervals for development
            - name: OTEL_METRICS_EXPORT_INTERVAL_SECONDS
              value: "5"
          
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 12