apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: globeco-portfolio-service-hpa
spec:
  minReplicas: 1
  maxReplicas: 3  # Limited scaling for development
  
  # More relaxed scaling for development
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180  # 3 minutes
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30   # 30 seconds
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
  
  # Higher thresholds for development (less aggressive scaling)
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80  # Scale when CPU > 80%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85  # Scale when memory > 85%