apiVersion: apps/v1
kind: Deployment
metadata:
  name: globeco-portfolio-service
spec:
  replicas: 2  # Two replicas for staging
  template:
    metadata:
      annotations:
        deployment.environment: "staging"
    spec:
      containers:
        - name: globeco-portfolio-service
          # Staging environment configuration
          env:
            # Environment Profile
            - name: PORTFOLIO_SERVICE_ENV
              value: "staging"
            - name: ENVIRONMENT
              value: "staging"
            
            # Monitoring Configuration (Staging - standard observability)
            - name: ENABLE_TRACING
              value: "true"   # Tracing enabled in staging
            - name: ENABLE_METRICS
              value: "true"
            - name: METRICS_SAMPLE_RATE
              value: "0.5"    # 50% sampling
            - name: OTEL_METRICS_EXPORT_INTERVAL_SECONDS
              value: "30"     # 30 second intervals
            
            # Middleware Configuration (Staging - selective middleware)
            - name: ENABLE_REQUEST_LOGGING
              value: "true"
            - name: ENABLE_METRICS_MIDDLEWARE
              value: "true"
            - name: ENABLE_THREAD_MONITORING
              value: "false"  # Disabled for performance
            - name: ENABLE_PERFORMANCE_PROFILING
              value: "false"
            
            # Logging Configuration (Staging - info level)
            - name: LOG_LEVEL
              value: "INFO"
            - name: ENABLE_REQUEST_RESPONSE_LOGGING
              value: "false"  # Disabled for performance
            - name: LOG_SAMPLING_RATE
              value: "0.5"    # 50% log sampling
            
            # Database Configuration (Staging - no tracing)
            - name: ENABLE_DATABASE_TRACING
              value: "false"  # Disabled for performance
            - name: ENABLE_QUERY_LOGGING
              value: "false"
            - name: MAX_POOL_SIZE
              value: "30"
            - name: MIN_POOL_SIZE
              value: "8"
            
            # Performance Configuration (Staging)
            - name: VALIDATION_CACHE_SIZE
              value: "1500"
          
          # Staging resource limits (balanced)
          resources:
            requests:
              cpu: "150m"
              memory: "192Mi"
            limits:
              cpu: "300m"
              memory: "384Mi"
          
          # Standard health checks for staging
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            initialDelaySeconds: 8
            periodSeconds: 12
          startupProbe:
            initialDelaySeconds: 12
            periodSeconds: 8
            failureThreshold: 12