apiVersion: apps/v1
kind: Deployment
metadata:
  name: globeco-portfolio-service
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: globeco-portfolio-service
          env:
            # Staging Environment Configuration
            - name: ENVIRONMENT
              value: "staging"
            - name: LOG_LEVEL
              value: "INFO"
            
            # Balanced Observability for Staging
            - name: ENABLE_METRICS
              value: "true"
            - name: ENABLE_TRACING
              value: "true"
            - name: ENABLE_DATABASE_TRACING
              value: "false"  # Disabled for performance
            - name: ENABLE_THREAD_METRICS
              value: "false"  # Disabled for performance
            - name: ENABLE_REQUEST_LOGGING
              value: "false"  # Disabled for performance
            - name: ENABLE_METRICS_MIDDLEWARE
              value: "true"
            - name: ENABLE_PERFORMANCE_PROFILING
              value: "false"
            
            # Staging Sampling (10%)
            - name: TRACE_SAMPLE_RATE
              value: "0.1"
            - name: METRICS_DEBUG_LOGGING
              value: "false"
            - name: THREAD_METRICS_DEBUG_LOGGING
              value: "false"
            
            # Standard export intervals
            - name: OTEL_METRICS_EXPORT_INTERVAL_SECONDS
              value: "30"
          
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "384Mi"
          
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10