apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: globeco-portfolio-service-hpa
spec:
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Balanced threshold for staging
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75  # Balanced threshold for staging
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 240  # Moderate scaling for staging
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 45   # Moderate scale up for staging
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max